### ISSUE TITLE
AIML 2.1 Rich Media tags like image, video(http://www.aiml.foundation/doc.html) is not supported.

### ISSUE THREAD

**Issue by ashishgupta-mca** [alejandro-du/vaadin-ai-chat#1]
I tried to include aiml 2.1 tags image, video, and hyperlink in aiml files but it doesn't work.
It seems org.goldrenard  1.0.7 doesn't have support for 2.1 aiml tags.

**Comment by alejandro-du** [comment]
I see. In that case, I guess there's not much I can do. Thanks for reporting this.
