### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Shruthi-Shree** [alejandro-du/vaadin-ai-chat#5]
Hello Alej..I followed through your build chatbot from Scratch tutorial and there is a step inside the application class to add ChatService() constructor..But where is the ChatService class actually defined and how is it being called ..My project compiles successfully but when I run it on the localhost:8080 ,it says, "You are offline
Chatbot project requires an internet connection to work. You do not seem to have access to the server right now. "
Can you please help me with this? Thank you.

**Comment by Shruthi-Shree** [comment]
@alejandro-du

**Comment by alejandro-du** [comment]
Hello. It seems like a mistake I made in the article text. There's no such class in the project indeed. I think you can ignore that constructor.
